# Generated by Django 5.0.6 on 2025-07-17 15:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("odhi", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="generalinfo",
            name="name",
        ),
        migrations.AddField(
            model_name="generalinfo",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="logos/"),
        ),
        migrations.AlterField(
            model_name="generalinfo",
            name="location",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
