# Generated by Django 5.1.3 on 2025-07-17 16:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("odhi", "0002_remove_generalinfo_name_generalinfo_logo_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="generalinfo",
            options={
                "verbose_name": "General Info",
                "verbose_name_plural": "General Info",
            },
        ),
    ]
