# Generated by Django 5.1.3 on 2025-07-21 07:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("odhi", "0005_hero_historicalhero"),
    ]

    operations = [
        migrations.RenameField(
            model_name="hero",
            old_name="name",
            new_name="title",
        ),
        migrations.RenameField(
            model_name="historicalhero",
            old_name="name",
            new_name="title",
        ),
    ]
