# Generated by Django 5.1.3 on 2025-07-22 14:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("odhi", "0008_remove_othervideo_thumbnail_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="othervideo",
            name="caption",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="othervideo",
            name="title",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="othervideo",
            name="youtube_link",
            field=models.URLField(),
        ),
    ]
