# Generated by Django 5.0 on 2025-07-23 15:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("odhi", "0009_alter_othervideo_caption_alter_othervideo_title_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="othervideo",
            name="artist",
            field=models.CharField(default="Odhi The Villager", max_length=100),
        ),
        migrations.AddField(
            model_name="othervideo",
            name="year",
            field=models.CharField(default=2018, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="othervideo",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="othervideo",
            name="youtube_link",
            field=models.URLField(
                help_text="Paste full YouTube URL e.g. https://www.youtube.com/watch?v=XXXXXXXXXXX"
            ),
        ),
    ]
