# Generated by Django 5.0 on 2025-07-23 19:39

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("odhi", "0011_eventtype_historicaleventtype"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EventMusic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("artist", models.CharField(max_length=100)),
                ("audio_file", models.FileField(upload_to="music/")),
                ("cover_image", models.ImageField(blank=True, upload_to="covers/")),
                ("preview_duration", models.IntegerField(default=60)),
            ],
            options={
                "verbose_name": "Event Music",
                "verbose_name_plural": "Event Music",
            },
        ),
        migrations.RemoveField(
            model_name="eventtype",
            name="audio_file",
        ),
        migrations.RemoveField(
            model_name="eventtype",
            name="cover_image",
        ),
        migrations.RemoveField(
            model_name="eventtype",
            name="image",
        ),
        migrations.RemoveField(
            model_name="eventtype",
            name="preview_duration",
        ),
        migrations.RemoveField(
            model_name="historicaleventtype",
            name="audio_file",
        ),
        migrations.RemoveField(
            model_name="historicaleventtype",
            name="cover_image",
        ),
        migrations.RemoveField(
            model_name="historicaleventtype",
            name="image",
        ),
        migrations.RemoveField(
            model_name="historicaleventtype",
            name="preview_duration",
        ),
        migrations.CreateModel(
            name="HistoricalEventMusic",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("artist", models.CharField(max_length=100)),
                ("audio_file", models.TextField(max_length=100)),
                ("cover_image", models.TextField(blank=True, max_length=100)),
                ("preview_duration", models.IntegerField(default=60)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Event Music",
                "verbose_name_plural": "historical Event Music",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
