# Generated by Django 5.0 on 2025-07-25 07:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("odhi", "0012_eventmusic_remove_eventtype_audio_file_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="eventmusic",
            name="audio_file",
        ),
        migrations.RemoveField(
            model_name="historicaleventmusic",
            name="audio_file",
        ),
        migrations.AddField(
            model_name="eventmusic",
            name="youtube_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicaleventmusic",
            name="youtube_link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
