# Generated by Django 5.1.3 on 2025-07-26 06:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("odhi", "0013_remove_eventmusic_audio_file_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="eventmusic",
            name="youtube_link",
        ),
        migrations.AddField(
            model_name="eventmusic",
            name="audio_file",
            field=models.FileField(
                default="music/Isanda - ODHI THE VILLAGER.mp3", upload_to="music/"
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="HistoricalEventMusic",
        ),
    ]
