# Generated by Django 5.0 on 2025-07-26 09:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("odhi", "0014_remove_eventmusic_youtube_link_eventmusic_audio_file_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LatestTrack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "artist",
                    models.CharField(default="Odhi The Villager", max_length=255),
                ),
                ("cover_image", models.ImageField(upload_to="track_covers/")),
                (
                    "audio_preview",
                    models.FileField(
                        blank=True, null=True, upload_to="audio_previews/"
                    ),
                ),
                ("buy_link", models.URLField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Latest Track",
                "verbose_name_plural": "Latest Tracks",
                "ordering": ["-created_at"],
            },
        ),
    ]
