# Generated by Django 5.1.3 on 2025-07-26 11:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("odhi", "0015_latesttrack"),
    ]

    operations = [
        migrations.CreateModel(
            name="Album",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("cover_image", models.ImageField(upload_to="album_covers/")),
                (
                    "album_link",
                    models.URLField(
                        help_text="Link to the album on SoundCloud, Spotify, etc."
                    ),
                ),
                ("release_date", models.DateField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Album",
                "verbose_name_plural": "Albums",
                "ordering": ["-release_date"],
            },
        ),
    ]
