# Generated by Django 5.1.3 on 2025-07-26 12:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("odhi", "0016_album"),
    ]

    operations = [
        migrations.RenameField(
            model_name="album",
            old_name="album_link",
            new_name="SoundCloud",
        ),
        migrations.AddField(
            model_name="album",
            name="apple_music_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="album",
            name="boomplay_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="album",
            name="hustlesasa_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="album",
            name="spotify_link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
