# Generated by Django 5.1.3 on 2025-07-26 13:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("odhi", "0017_rename_album_link_album_soundcloud_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="album",
            name="SoundCloud",
            field=models.URLField(help_text="Link to the album on SoundCloud"),
        ),
        migrations.AlterField(
            model_name="album",
            name="apple_music_link",
            field=models.URLField(
                blank=True, help_text="Link to the album on Apple Music", null=True
            ),
        ),
        migrations.AlterField(
            model_name="album",
            name="boomplay_link",
            field=models.URLField(
                blank=True, help_text="Link to the album on Boomplay", null=True
            ),
        ),
        migrations.AlterField(
            model_name="album",
            name="hustlesasa_link",
            field=models.URLField(
                blank=True, help_text="Link to the album on HustleSasa", null=True
            ),
        ),
        migrations.AlterField(
            model_name="album",
            name="spotify_link",
            field=models.URLField(
                blank=True, help_text="Link to the album on Spotify", null=True
            ),
        ),
    ]
