# Generated by Django 5.0 on 2025-07-26 13:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("odhi", "0018_alter_album_soundcloud_alter_album_apple_music_link_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="album",
            name="youtube_link",
            field=models.URLField(
                blank=True, help_text="Link to the album on YouTube", null=True
            ),
        ),
    ]
