# Generated by Django 5.0 on 2025-07-26 13:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("odhi", "0019_album_youtube_link"),
    ]

    operations = [
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=255)),
                ("answer", models.TextField()),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Set the display order"
                    ),
                ),
            ],
            options={
                "verbose_name": "FAQ",
                "verbose_name_plural": "FAQs",
                "ordering": ["order"],
            },
        ),
    ]
