# Generated by Django 5.0 on 2025-07-26 14:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("odhi", "0020_faq"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="faq",
            options={"verbose_name": "FAQ", "verbose_name_plural": "FAQs"},
        ),
        migrations.RemoveField(
            model_name="faq",
            name="order",
        ),
    ]
