# Generated by Django 5.0 on 2025-07-29 08:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("odhi", "0021_alter_faq_options_remove_faq_order"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subscriber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("date_subscribed", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
