# Generated by Django 5.0 on 2025-07-31 14:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("odhi", "0022_subscriber"),
    ]

    operations = [
        migrations.CreateModel(
            name="Blogs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "blog_image",
                    models.ImageField(blank=True, null=True, upload_to="blog_images/"),
                ),
                ("category", models.CharField(blank=True, max_length=100, null=True)),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
                (
                    "author",
                    models.CharField(
                        default="Kepher Odhiambo Mak'Anyengo", max_length=100
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "verbose_name": "Blog",
                "verbose_name_plural": "Blogs",
                "ordering": ["-created_at"],
            },
        ),
    ]
