# Generated by Django 5.0 on 2025-07-31 16:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("odhi", "0023_blogs"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogs",
            name="link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
