# Generated by Django 5.0 on 2025-08-07 19:56

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("odhi", "0025_newslettersubscriber"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogs",
            name="content",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
