# Generated by Django 5.0 on 2025-08-08 07:34

import django.utils.timezone
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("odhi", "0027_comment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Comment",
                "verbose_name_plural": "Comments",
            },
        ),
        migrations.RenameField(
            model_name="comment",
            old_name="active",
            new_name="approved",
        ),
        migrations.RenameField(
            model_name="comment",
            old_name="body",
            new_name="comment",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="created_on",
        ),
        migrations.AddField(
            model_name="comment",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="blogs",
            name="content",
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name="comment",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="comment",
            name="phone_number",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
