# Generated by Django 5.0 on 2025-10-14 11:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("odhi", "0028_alter_comment_options_rename_active_comment_approved_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("release_datetime", models.DateTimeField()),
                (
                    "video_file",
                    models.FileField(blank=True, null=True, upload_to="videos/"),
                ),
                ("youtube_link", models.URLField(blank=True, null=True)),
            ],
        ),
    ]
