# Generated by Django 5.0 on 2025-10-14 16:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("odhi", "0029_video"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("date", models.DateField()),
                ("image", models.ImageField(upload_to="events/")),
                (
                    "platform",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("place", "Physical Place"),
                            ("youtube", "YouTube"),
                            ("itunes", "iTunes"),
                            ("soundcloud", "SoundCloud"),
                            ("apple_music", "Apple Music"),
                            ("hustlesasa", "HustleSasa"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "location_detail",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
    ]
