# Generated by Django 5.0 on 2025-10-14 16:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("odhi", "0030_event"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="location_detail",
            new_name="place",
        ),
        migrations.RemoveField(
            model_name="event",
            name="platform",
        ),
        migrations.AddField(
            model_name="event",
            name="apple_music",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="hustlesasa",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="itunes",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="other",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="soundcloud",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="youtube",
            field=models.URLField(blank=True, null=True),
        ),
    ]
