"""
Django settings for OdhiTheVillager project.

Generated by 'django-admin startproject' using Django 5.0.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url

RAILWAY_DOMAIN = os.environ.get("RAILWAY_PUBLIC_DOMAIN")
RAILWAY_SERVICE_DOMAIN = os.environ.get("RAILWAY_PRIVATE_DOMAIN")

ALLOWED_HOSTS = ["localhost", "127.0.0.1"]

if RAILWAY_DOMAIN:
    ALLOWED_HOSTS.append(RAILWAY_DOMAIN)

if RAILWAY_SERVICE_DOMAIN:
    ALLOWED_HOSTS.append(RAILWAY_SERVICE_DOMAIN)

# Optional: allow Railway's default *.up.railway.app domain
ALLOWED_HOSTS.append("odhithevillagerbackend-production.up.railway.app")

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-g!8x(=e%bk6s-9%d8y5+fz!0cq7o2y9v%^bgsij%e(@*2w3jpw"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True


RAILWAY_APP_HOSTNAME = os.getenv('RAILWAY_DOMAIN')

# Add the hostname to your allowed hosts
ALLOWED_HOSTS = [
    RAILWAY_APP_HOSTNAME,
    'localhost',
    '127.0.0.1',
]


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "odhi",
    'simple_history',
    'tinymce',
    'widget_tweaks',
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    'simple_history.middleware.HistoryRequestMiddleware',
]

ROOT_URLCONF = "OdhiTheVillager.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            os.path.join(BASE_DIR, "templates")
            ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "odhi.context_processors.newsletter_form",
                "odhi.context_processors.general_info",
                
            ],
        },
    },
]

WSGI_APPLICATION = "OdhiTheVillager.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.parse(
        os.getenv("DATABASE_URL", "sqlite:///db.sqlite3")
    )
}

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Africa/Nairobi"

USE_I18N = True

USE_TZ = True



STATIC_URL = "/static/"

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

JAZZMIN_SETTINGS = {
    "site_title": "Odhi The Villager Admin",
    "site_header": "Odhi Admin Panel",
    "welcome_sign": "Manage Odhi The Villager Content",
    "site_logo": "img/logo.png",  # must be in your static folder
    "copyright": "Odhi The Villager © 2025",

    "topmenu_links": [
        {"name": "Dashboard", "url": "admin:index"},
        {"name": "View Site", "url": "/", "new_tab": True},
    ],
     "order_with_respect_to": [
        "auth", "odhi.Blog", "odhi.Album", "odhi.Comment",
        "odhi.EventMusic", "odhi.EventType", "odhi.FAQ",
        "odhi.GeneralInfo", "odhi.Hero", "odhi.LatestTrack",
        "odhi.OtherVideo"
    ],

    "icons": {
        "odhi.Blogs": "fas fa-blog",
        "odhi.Comment": "fas fa-comments",
        "auth.User": "fas fa-user",
        "auth.User": "fas fa-user",
        "odhi.Albums": "fas fa-music",
        "odhi.EventMusic": "fas fa-guitar",
        "odhi.EventType": "fas fa-calendar",
        "odhi.FAQ": "fas fa-question-circle",
        "odhi.GeneralInfo": "fas fa-info-circle",
        "odhi.Hero": "fas fa-star",
        "odhi.LatestTrack": "fas fa-headphones",
        "odhi.OtherVideo": "fas fa-video",
    },
}
